inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

inherit_gem:
  prettier: rubocop.yml

require: 
  - rubocop-faker
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/spg_client/fake/*.rb'

Style/GlobalVars:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
